import Head from "next/head";
import styles from "@component/styles/Home.module.css";
import {useState} from "react";
import {useRouter} from "next/router";


export default function Layout({ children }) {
    const [searchText, setSearchText] = useState('');
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <a href={'/'}>GitHub Explorer </a>
            <input
                type="text"
                value={searchText}
                onChange={e => { setSearchText(e.currentTarget.value); }}
                //onKeyUp={(event) => {checkAnswer(event, searchText)}}
            />
            <button onClick={()=>{router.push('/user/'+searchText)}}>Search</button>
            <main>
           {children}</main>

        </>
    )
}